"""additional columns

Revision ID: 3b2f2014733a
Revises: 7a1d20414980
Create Date: 2017-11-02 05:48:32.700622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2f2014733a'
down_revision = '7a1d20414980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_constraint('categories_pitch_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'pitch_id')
    op.drop_column('categories', 'username')
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'category_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitch_id')
    op.add_column('categories', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_pitch_id_fkey', 'categories', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('categories', 'name')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
