"""change the relationship btn comments and users

Revision ID: 7fe91a620571
Revises: 552790f559b9
Create Date: 2017-11-01 09:26:03.087033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe91a620571'
down_revision = '552790f559b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitches_comment_id_fkey', 'pitches', type_='foreignkey')
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'comment_id')
    op.drop_column('pitches', 'user_id')
    op.add_column('users', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'users', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'comment_id')
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'users', ['user_id'], ['id'])
    op.create_foreign_key('pitches_comment_id_fkey', 'pitches', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
